/* eslint-disable no-undef */

import {  Config, Flags } from "lighthouse";

export const LIGHTHOUSE_THRESHOLDS:  Record<string, number> = {
  performance: 80,
  accessibility: 80,
  'best-practices':80
};

export const LIGHTHOUSE_OPTIONS: Flags = {
  formFactor: 'desktop',
  screenEmulation: {
    mobile: false,
    disabled: false,
    width: 1920,
    height: 1080,
    deviceScaleFactor: 1,
  },
  throttling: {
    rttMs: 40,
    throughputKbps: 11024,
    cpuSlowdownMultiplier: 1,
    requestLatencyMs: 0,
    downloadThroughputKbps: 0,
    uploadThroughputKbps: 0,
  },
  output: 'html',
};

export const LIGHTHOUSE_CONFIG: Config = {
  extends: 'lighthouse:default', 
  settings: { 
      pauseAfterLoadMs: 1000,
      networkQuietThresholdMs: 1000
  }
};

export interface LighthousePaths {
  reportsPath: string;
  lighthouseReportsPath: string;
}

export const LIGHTHOUSE_PATHS: LighthousePaths = {
  reportsPath: './reports/',
  lighthouseReportsPath: './reports/lighthouse/',
};

export interface LighthouseReportOptions {
  minifyHtmlReports: boolean;
  htmlMinifierOptions: Record<string, boolean>;
  fileName : string;
}

export const LIGHTHOUSE_REPORT_OPTIONS: LighthouseReportOptions = {
  minifyHtmlReports: true,
  fileName:'',
  htmlMinifierOptions: {
    includeAutoGeneratedTags: true,
    removeAttributeQuotes: true,
    removeComments: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    sortClassName: true,
    useShortDoctype: true,
    collapseWhitespace: true,
    minifyCSS: true,
    minifyJS: true,
  },
};
